`import "./mixin_spec"`
`import "./object_spec"`
`import "./property_spec"`
`import "./can_have_parent_spec"`
`import "./can_group_spec"`
`import "./canvas_spec"`
`import "./color_spec"`
`import "./transform_spec"`
`import "./group_spec"`
`import "./matrix2d_spec"`
`import "./tree_iterator_spec"`
`import "./sprite_spec"`
`import "./game_object_spec"`
`import "./p2_physics_spec"`
`import "./vector2d_spec"`
`import "./asset_loader_spec"`
