`import "./mixin_spec"`
`import "./object_spec"`
`import "./property_spec"`
`import "./can_have_parent_spec"`
`import "./can_group_spec"`
`import "./canvas_spec"`
`import "./color_spec"`
`import "./transform_spec"`
`import "./matrix2d_spec"`
